Add a check in `test-all` to verify the TF versions in different location
The `run-valgrind` script fails silently if its Tensorflow version is not
the proper one. The reason is because the `export LD_LIBRARY_PATH` line
explicitly uses the TF version in the exported path. If it is wrong (for
example if the version defined in variable `tensorflow_version` near the
top of the file) then the first call to valgrind will fail.

All the output of the call to valgrind is sent to a log file, so the
failure is not reported. And since the first line of the script let it
abort on error (`set -e`), the script stop on the first call to valgrind.

This commit adds a check in the `test-all` script to make sure the version
values match where they appear. This should let the CI fail if the
TF versioning is wrong in the crates.

diff --git a/test-all b/test-all
--- a/test-all
+++ b/test-all
@@ -2,6 +2,18 @@
 
 set -e
 
+# Make sure the Tensorflow version in the -sys build script matches the one in
+# the run-valgrind script.
+version_build_script=`grep "const VERSION" tensorflow-sys/build.rs | sed 's|.*"\([0-9\.]*\)";|\1|g'`
+version_run_valgrind=`grep "tensorflow_version=" run-valgrind | sed "s|.*=\(.*\)|\1|g"`
+if [[ "${version_build_script}" != "${version_run_valgrind}" ]]; then
+    echo "ERROR: Tensorflow version specified in build script does not match the one in the"
+    echo "       valgrind run script."
+    echo "       tensorflow-sys/build.rs: ${version_build_script}"
+    echo "       run-valgrind: ${version_run_valgrind}"
+    exit 1
+fi
+
 cargo test -vv -j 2 --features tensorflow_unstable
 cargo run --example regression
 cargo run --features tensorflow_unstable --example expressions
